stages:
  load_data:
    cmd: python src/stage_01_load_save.py --config=config/config.yaml
    deps:
      - config\config.yaml
      - src\stage_01_load_save.py
      - src\utils\all_utils.py
    outs:
      - artifacts\raw_local_dir\data.csv
