stages:
  load_data:
    cmd: python src/stage_01_load_save.py --config=config/config.yaml
    deps:
      - config/config.yaml
      - src/stage_01_load_save.py
      - src/utils/all_utils.py
    outs:
      - artifacts/raw_local_dir/data.csv

  split_data:
    cmd: python src/stage_02_split_data.py --config=config/config.yaml --params=params.yaml
    deps:
      - config/config.yaml
      - src/stage_02_split_data.py
      - src/utils/all_utils.py
    params:
      - base.random_state
      - base.test_size
    outs:
      - artifacts/split_data_dir/train.csv
      - artifacts/split_data_dir/test.csv

